FROM ghcr.io/christoffercarlsson/devcontainers/rust@sha256:42aca334f7fffde2d3a26eb8a48552fe2a34ac823ea4f3940146684181cffb99 AS builder

ARG VERIFPAL_VERSION=1.4.8

RUN git clone --depth 1 --branch "v${VERIFPAL_VERSION}" \
        https://github.com/symbolicsoft/verifpal /tmp/verifpal \
    && cd /tmp/verifpal \
    && cargo build --release

FROM ghcr.io/christoffercarlsson/devcontainers/rust@sha256:42aca334f7fffde2d3a26eb8a48552fe2a34ac823ea4f3940146684181cffb99 AS runtime

COPY --from=builder /tmp/verifpal/target/release/verifpal /usr/local/bin/verifpal

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/autograph
