FROM ghcr.io/christoffercarlsson/devcontainers/rust@sha256:fb378b967dbf72c3701524352f112ee31271c4c4678de144a8d67edcd623f39f AS builder

ARG VERIFPAL_VERSION=1.4.11

RUN git clone --depth 1 --branch "v${VERIFPAL_VERSION}" \
        https://github.com/symbolicsoft/verifpal /tmp/verifpal \
    && cd /tmp/verifpal \
    && cargo build --release

FROM ghcr.io/christoffercarlsson/devcontainers/rust@sha256:fb378b967dbf72c3701524352f112ee31271c4c4678de144a8d67edcd623f39f AS runtime

COPY --from=builder /tmp/verifpal/target/release/verifpal /usr/local/bin/verifpal

ENTRYPOINT ["/usr/local/sbin/entrypoint"]

LABEL org.opencontainers.image.source=https://github.com/christoffercarlsson/autograph
