#!/bin/sh

SOURCE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SODIUM_INCLUDE_DIR="$SOURCE_DIR/libsodium/src/libsodium/include/sodium"
SODIUM_VERSION="1.0.19"
SODIUM_LIBRARY_VERSION_MAJOR=26
SODIUM_LIBRARY_VERSION_MINOR=1

sed -e "s/@VERSION@/$SODIUM_VERSION/g" \
    -e "s/@SODIUM_LIBRARY_VERSION_MAJOR@/$SODIUM_LIBRARY_VERSION_MAJOR/g" \
    -e "s/@SODIUM_LIBRARY_VERSION_MINOR@/$SODIUM_LIBRARY_VERSION_MINOR/g" \
    -e "s/@SODIUM_LIBRARY_MINIMAL_DEF@//" \
    < "$SODIUM_INCLUDE_DIR/version.h.in" \
    > "$SODIUM_INCLUDE_DIR/version.h"
