set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_OSX_SYSROOT "appletvos")

set(CMAKE_OSX_DEPLOYMENT_TARGET "11.0" CACHE STRING "Minimum tvOS deployment target")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -arch ${AUTOGRAPH_ARCH} -mtvos-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -arch ${AUTOGRAPH_ARCH} -mtvos-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}")
set(CMAKE_XCODE_ATTRIBUTE_TVOS_DEPLOYMENT_TARGET "${CMAKE_OSX_DEPLOYMENT_TARGET}")

# Set the tvOS target platform version
set(CMAKE_XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY "3")
