set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_OSX_SYSROOT "watchos")

if (AUTOGRAPH_ARCH STREQUAL "armv7k")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mthumb")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mthumb")
endif()

set(CMAKE_OSX_DEPLOYMENT_TARGET "5.0" CACHE STRING "Minimum watchOS deployment target")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -arch ${AUTOGRAPH_ARCH} -mwatchos-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -arch ${AUTOGRAPH_ARCH} -mwatchos-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}")
set(CMAKE_XCODE_ATTRIBUTE_WATCHOS_DEPLOYMENT_TARGET "${CMAKE_OSX_DEPLOYMENT_TARGET}")

# Set the watchOS target platform version
set(CMAKE_XCODE_ATTRIBUTE_TARGETED_DEVICE_FAMILY "4")
